### PR TITLE
Improve ES2K driver interface

### PR DESCRIPTION
**Pull request by ffoulkes**
This CL makes P4 Control Plane more robust in the face of changes to the internal structure of the ES2K SDE.

- Remove target definitions for all libraries that are transitive dependencies of the SDE libraries that P4 Control Plane calls directly. We do not require them.

- Search a list of known locations to find the directory in which the SDE installed the DPDK (RTE) libraries. If we find a match, add it to the link directory list. This allows the linker to resolve transitive dependencies on DPDK libraries at build time.

  These changes reduce coupling between P4 Control Plane and the SDE. This should give us better forward and backward compatibility with different releases of the SDE.

  These changes also remove all the special-case logic. We no longer need to deal with libraries that don't specify an `SONAME`, nor do we have to choose between `xeoncp` and `acccp`, or between `rte_net_idpf` and `rte_net_cpfl`.

- Add definitions for the `target_sys`, `tdi`, and `tdi_json_parser` libraries. All of them are direct dependencies of `infrap4d`.

- Remove the `_define_es2k_libs()` function. It was a workaround for a problem we have since solved.

### CODE REVIEW

**Comment by ffoulkes** [comment]
I tested:

1. Build for x86 target against an older SDE on Ubuntu 20.04 running under WSL.
2. Build for x86 target against a newer SDE (/root/pv/0.9.0/cpfl-change/p4-sde/install/lib/x86_64-linux-gnu) on Sandeep's Ubuntu machine.
3. Cross-compilation for aarch64 target against an older SDE (`/opt/p4/p4sde`) on Sandeep's Ubuntu machine.

 I haven't been able to build the SDE on Fedora. Based on one of my failed attempts, I've posited that the Fedora build installs the RTE libraries in `<installdir>/lib64`, and have updated es2k-driver.cmake to check for this.

**Comment by n-sandeep** [comment]
> I tested:
> 
> 1. Build for x86 target against an older SDE on Ubuntu 20.04 running under WSL.
> 2. Build for x86 target against a newer SDE (/root/pv/0.9.0/cpfl-change/p4-sde/install/lib/x86_64-linux-gnu) on Sandeep's Ubuntu machine.
> 3. Cross-compilation for aarch64 target against an older SDE (`/opt/p4/p4sde`) on Sandeep's Ubuntu machine.
> 
> I haven't been able to build the SDE on Fedora. Based on one of my failed attempts, I've posited that the Fedora build installs the RTE libraries in `<installdir>/lib64`, and have updated es2k-driver.cmake to check for this.

I can cross compile with latest SDE tomorrow and get back Derek. I can approve the changes once cross compile is successful with latest SDE

**Comment by ffoulkes** [comment]
> I can cross compile with latest SDE tomorrow and get back Derek. I can approve the changes once cross compile is successful with latest SDE

That would be great. Thank you!

**Comment by ffoulkes** [comment]
> I can cross compile with latest SDE tomorrow and get back Derek. I can approve the changes once cross compile is successful with latest SDE

@n-sandeep has tested this PR on Fedora, and confirms that it works. (Thanks, Sandeep!)

**Review by nupuruttarwar — APPROVED** [review]
This is a great improvement! 
LGTM

**Review by satish153 — APPROVED** [review]
LGTM

**Review by 5abeel — APPROVED** [review]
LGTM

**Pull request merged**
