### PR TITLE
enabled dependabot for pip/github-action packages

### PR DESCRIPTION
**Pull request by ipdksw**
PR to enable depondabot scan for pip and github actions
More info: https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide

### CODE REVIEW

**Review by ffoulkes — APPROVED** [review]
The PR should include a changelist comment explaining the purpose / nature of the change.

I've been using YAML for a number of years, but I had to look up the meaning of three hyphens.

They're really not appropriate here. The hyphens mark the start of a document when you need a separator. The comment block is documentation for the YAML that follows, so it's part of the same document.

Harmless in this case, but still inappropriate.

**Comment by ipdksw** [comment]
> The PR should include a changelist comment explaining the purpose / nature of the change.
> 
> I've been using YAML for a number of years, but I had to look up the meaning of three hyphens.
> 
> They're really not appropriate here. The hyphens mark the start of a document when you need a separator. The comment block is documentation for the YAML that follows, so it's part of the same document.
> 
> Harmless in this case, but still inappropriate.

Thanks Derek, updated the PR description!

**Review by 5abeel — APPROVED** [review]
LGTM

Just one minor comment: Do we need to check for daily updates? pip packages are not updated that frequently.

**Comment by mgaravin** [comment]
> LGTM
> 
> Just one minor comment: Do we need to check for daily updates? pip packages are not updated that frequently.

@5abeel : will change the frequency once we have report for SDLe.

**Comment by ffoulkes** [comment]
Hi Aravind,

You should probably enable Dependabot for github actions on:

  *   ipdk-io/krnlmon
  *   ipdk-io/stratum-deps
  *   idpk-io/stratum-dev

What’s the scope of the pip scanning?

  *   pip commands in github workflows?
  *   Files in the repository (and, if so, what kinds of files)?

Best regards,
Derek

**Pull request merged**
