### PR TITLE
Set recommended compiler flags

### PR DESCRIPTION
**Pull request by ffoulkes**
- Set C and C++ compiler flags according to the Intel Secure Coding Standards.

### CODE REVIEW

**Comment by ffoulkes** [comment]
Unfortunately, throwing in all the compiler flags IPAS recommends makes us incompatible with libraries that aren't built with (some of) the flags we're now specifying. It's going to take a while to figure out which options are causing the problems and find a way to deal with it.

I've worked around it for now by adding support for "legacy" legacy -- replicating the settings we used when cross-compiling for ACC.

In the meantime, this module is a significant improvement over the existing code.

**Comment by ffoulkes** [comment]
I don't have access to a system that allows me to verify that the code cross-compiles for ACC. I'm working on solving that problem, but it might be quicker if someone else can test it for me.

I have no intention of merging this PR until we've verified that it does not break the ACC build.

**Review by 5abeel — APPROVED** [review]
LGTM

**Review by nupuruttarwar — APPROVED** [review]
LGTM

**Pull request merged**
