### PR TITLE
Support build types in dependency build

### PR DESCRIPTION
**Pull request by ffoulkes**
- Modify setup/CMakeLists.txt to forward the CMAKE_BUILD_TYPE variable to each component it builds.

- Add missing CMAKE_TOOLCHAIN_FILE option when building gflags.

### CODE REVIEW

**Review by nupuruttarwar — APPROVED** [review]
lgtm

**Comment by ffoulkes** [comment]
These changes were prompted by the suggestion that we build the dependencies (specifically gRPC and Protobuf) in Release mode and see whether we see an improvement in gRPC throughput. A `Release` build is compiled at optimization level `-O3`, which is higher than `RelWithDebInfo` (`-O2`) or `Debug`.

**Comment by 5abeel** [comment]
> These changes were prompted by the suggestion that we build the dependencies (specifically gRPC and Protobuf) in Release mode and see whether we see an improvement in gRPC throughput. A `Release` build is compiled at optimization level `-O3`, which is higher than `RelWithDebInfo` (`-O2`) or `Debug`.

Im not sure I follow how this works. How does setting the CMAKE_BUILD_TYPE change the compiler optimization level?

**Comment by ffoulkes** [comment]
> Im not sure I follow how this works. How does setting the CMAKE_BUILD_TYPE change the compiler optimization level?

CMAKE_BUILD_TYPE specifies the name of a _Build Configuration_ -- a named set of compile/link parameters that correspond to a particular type of build. CMake has four predefined types (Debug, MinSizeRel, Release, and RelWithDebInfo) plus the blank or undefined type.

The associated C++ compile flags are:
```
CMAKE_CXX_FLAGS == ""
CMAKE_CXX_FLAGS_DEBUG == "-g"
CMAKE_CXX_FLAGS_MINSIZEREL == "-Os -DNDEBUG"
CMAKE_CXX_FLAGS_RELEASE == "-O3 -DNDEBUG"
CMAKE_CXX_FLAGS_RELWITHDEBINFO == "-O2 -g -DNDEBUG"
```

**Review by 5abeel — APPROVED** [review]
LGTM

**Review by n-sandeep — APPROVED** [review]
LGTM

**Pull request merged**
