### PR TITLE
Add SDE_INSTALL_DIR and DEPEND_INSTALL_DIR checks

### PR DESCRIPTION
**Pull request by ffoulkes**
- Generate fatal error if SDE_INSTALL_DIR is not defined.

### CODE REVIEW

**Review by nupuruttarwar — COMMENTED** [review]
change LGTM, should be checking other variables as well which are derived from env variables, say DEPEND_INSTALL?

**Comment by ffoulkes** [comment]
> change LGTM, should we be checking other variables as well which are derived from env variables, say DEPEND_INSTALL?

Not necessarily. I just remembered why I didn't require that the various xxxx_INSTALL_DIR variables be defined.

The original premise was that all the packages would be installed to the same directories. I introduced support for separate directories, partly to make it easier to work on one package at a time during development, and partly to support Google's recommendation that gRPC and Protobuf _not_ be installed to system directories.

There are also a couple of use cases that don't necessarily require the full build infrastructure. It is currently possible to build and run the kernel monitor unit tests with nothing but target-syslibs. (Once we add switchlink_db unit testing, we will also need tommyds, which is part of target-utils.)

If we're not careful, we'll end up burdening simple tasks with the weight of the entire build. I'm not convinced that requiring something we don't actually need is better than erroring out with an undefined library.

**Comment by nupuruttarwar** [comment]
I understand that part of krnlmon unit tests(switchlink module mainly) can built without SDE and also agree about not burdening simple tasks with the weight of the entire build.  But switchapi component in krnlmon accesses TDI API's, so we will need to have SDE libraries for unit testing switchapi module. We will add that support once we get there anyways.

My question about checking DEPEND_INSTALL was more about when are doing overall build using cmake command or make-all.sh.
make-all.sh checks if _SDE_DIR is non-empty but doesn't check _DEPS_DIR even though the build depends on both. Thoughts?

**Comment by ffoulkes** [comment]
> switchapi component in krnlmon accesses TDI API's, so we will need to have SDE libraries for unit testing switchapi module. We will add that support once we get there anyways.

Code that accesses the actual hardware libraries is an integration test, not a unit test. Either we mock the SDE interface or we don't unit-test the code.

**Comment by ffoulkes** [comment]
> make-all.sh checks if _SDE_DIR is non-empty but doesn't check _DEPS_DIR even though the build depends on both. Thoughts?

Stratum is no longer an optional component. I think it's safe to say that P4 Control Plane is inherently dependent on the Stratum dependencies.

It costs us little at build time to be dependent on the SDE and Stratum dependencies. These dependencies are built and installed independently of the P4 Control Build.

The real build-time cost is in the number of source files (especially C++ and Protobuf) we have to compile. The optimizations in the kernel monitor testing path come from our target selection and the number of P4 Control Plane source files the targets require. The SDE and Stratum dependencies don't figure into this.

There is therefore no real risk in requiring that DEPEND_INSTALL be defined.

And in the event that the original scenario occurs (SDE and Stratum dependencies share an install tree), we should be able to finesse the check by setting SDE_INSTALL and DEPEND_INSTALL to the same file path.

I will amend the PR to perform a second check.

**Comment by ffoulkes** [comment]
Well-spotted and well-argued, by the way.

**Pull request merged**
