### PR TITLE
Stratum cmake support

### PR DESCRIPTION
**Pull request by ffoulkes**
- Move basic cmake build support from the superproject into the stratum project. Protobuf generation and compilation is still part of the networking-recipe.
- Replace our implementation of FindUnwind with one taken from the glog project. This resolves a conflict between the two versions. Add copyright notice, SPDX license identifier, and link to the license file in the glog project.
- Change target library references to unwind::unwind.

### CODE REVIEW

**Comment by ffoulkes** [comment]
This PR is substantially the same as one made by @ravi861 in November 2022 (https://github.com/ipdk-io/networking-recipe/pull/43).

**Comment by ffoulkes** [comment]
We really should go ahead and merge these changes. They simplify future updates considerably.

**Review by nupuruttarwar — APPROVED** [review]
LGTM

**Review by satish153 — APPROVED** [review]
LGTM

**Comment by ffoulkes** [comment]
This completes the initial cmake-stratum migration. I've just done successful builds of the DPDK, ES2K, and Tofino targets and am about to test cross-compilation of ES2K.

**Comment by ffoulkes** [comment]
Success. I'm able to cross-compile for ACC-RL.

**Review by 5abeel — APPROVED** [review]
LGTM

**Pull request merged**
