### PR TITLE
Adding MAC addresses to logs when failure occurs (#498)

### PR DESCRIPTION
**Pull request by 5abeel**
This PR cherry-picks #498 to `main` branch

### CODE REVIEW

**Review by ffoulkes — APPROVED** [review]
Please run clang-format on ovsp4rt.cc.

**Comment by 5abeel** [comment]
> Please run clang-format on ovsp4rt.cc.

Ran it and now all checks pass. I dont see the button enabled - can you please merge it?

**Comment by ffoulkes** [comment]
Oh, I get it. clang-format is using four-space indentation because it's within a parameter list.

**Review by ffoulkes — APPROVED** [review]
LGTM

**Pull request merged**
