### PR TITLE
Update krnlmon submodule

### PR DESCRIPTION
**Pull request by ffoulkes**
- Makes LNW_V2 and LNW_V3 available in ovs-p4rt.
- Adds support for dummy_krnlmon target.
- Modifies krnlmon-test to specify --output-on-failure.

### CODE REVIEW

**Comment by nupuruttarwar** [comment]
Please check why krnlmon unit tests are failing.

**Comment by ffoulkes** [comment]
> Please check why krnlmon unit tests are failing.

Fixed in https://github.com/ipdk-io/krnlmon/pull/117.

**Review by 5abeel — APPROVED** [review]
LGTM

**Review by nupuruttarwar — APPROVED** [review]
LGTM

**Pull request merged**
