### PR TITLE
Add Ninja support

### PR DESCRIPTION
**Pull request by ffoulkes**
- Modify P4 Control Plane so it can be built with Ninja.
- Implement `--ninja` option in `make-all.sh`.
- Implement `--config` option in `make-all.sh`.
- Update krnlmon submodule reference.

Depends on https://github.com/ipdk-io/krnlmon/pull/48.

### CODE REVIEW

**Comment by ffoulkes** [comment]
P4 Control Plane builds successfully with Ninja.
OVS does not.

**Comment by ffoulkes** [comment]
Note that Ninja builds are a work in progress.
This PR implements the `--ninja` option but doesn't include it in the help text.
It also adds the `--config` option to configure without building.

**Comment by ffoulkes** [comment]
> LGTM, please resolve the conflicts before merging.

Conflicts resolved.

**Review by 5abeel — APPROVED** [review]
LGTM

**Pull request merged**
