### PR TITLE
Update CMakeLists to compile credentials_manager

### PR DESCRIPTION
**Pull request by 5abeel**
To be merged after Credentials_Manager is updated in stratum-dev repo (PR: https://github.com/ipdk-io/stratum-dev/pull/57)

Signed-off-by: Sabeel Ansari <sabeel.ansari@intel.com>

### CODE REVIEW

**Review by vsureshkumarp — APPROVED** [review]
Changes looks good to me.

**Review by ffoulkes — CHANGES_REQUESTED** [review]
1. The changelist will need to update the `stratum` submodule pointer to a commit that includes the new files.
2. The CI/CD chain is reporting compilation errors. Have these been investigated?

**Comment by 5abeel** [comment]
@ffoulkes Is that done before the Stratum changes merge into repo? I thought the workflow was to let it merge first, update the submodule pointer and then re-run the CI/CD pipeline here.

**Comment by ffoulkes** [comment]
> @ffoulkes Is that done before the Stratum changes merge into repo? I thought the workflow was to let it merge first, update the submodule pointer and then re-run the CI/CD pipeline here.

The workflow acts based on the content of the changelist. Your original commit did not update the submodule pointer, so the CI/CD chain would have attempted to build against an older Stratum commit (one without any of your changes).

Your pushed-but-not-current changes are only visible if someone manually changes the commit ID of the `stratum/stratum` submodule. The CI/CD compile errors are what led me to discover that you hadn't updated the submodule pointer.

**Pull request closed without merging**
