### PR TITLE
Update name to use p4cp.recipe and other minor formatting changes

### PR DESCRIPTION
**Pull request by 5abeel**

### CODE REVIEW

**Review by ffoulkes — APPROVED** [review]
LGTM

Though `p4cp.recipe` is a poor substitute for `ipdk.recipe`.
P4 Control Plane == Networking Recipe
It would more appropriate to call it `nw.recipe` or just `recipe`.
My personal favorite is `nwrx`.
Rx = Recipe = Prescription 
Isn't etymology fun? 😎

**Comment by 5abeel** [comment]
> LGTM
> 
> Though `p4cp.recipe` is a poor substitute for `ipdk.recipe`. P4 Control Plane == Networking Recipe It would more appropriate to call it `nw.recipe` or just `recipe`. My personal favorite is `nwrx`. Rx = Recipe = Prescription Isn't etymology fun? 😎

Since the P4CP_RECIPE env var was used elsewhere in documentation, I stuck with it. I like the idea of a `nw.recipe` and think that is a more apt name (since external users may not be familiar with the `P4CP` name)

**Comment by ffoulkes** [comment]
> Since the P4CP_RECIPE env var was used elsewhere in documentation, I stuck with it. I like the idea of a `nw.recipe` and think that is a more apt name (since external users may not be familiar with the `P4CP` name)

Of course you did. It's low impact, and it's the logical thing to do. _Sigh_.

**Review by Namrata-intel — APPROVED** [review]

**Review by nupuruttarwar — APPROVED** [review]
LGTM

**Pull request merged**
