### PR TITLE
disable libcapng by default during build

### PR DESCRIPTION
**Pull request by umohi**
disable libcapng by default to provide a way deal with inconsistencies in system packages installed in various linux distros

### CODE REVIEW

**Review by ffoulkes — COMMENTED** [review]
Please remove the `--disable-libcapng` at line 181.

Oh, I should have mentioned ... you need to sign your commits. (`git commit -s`). If you don't the DCO check can fail. I can override it this time, but you may find me less merciful in the future.

image

**Review by ffoulkes — APPROVED** [review]
LGTM

**Review by 5abeel — APPROVED** [review]
LGTM

**Comment by umohi** [comment]
> Please remove the `--disable-libcapng` at line 181.
> 
> Oh, I should have mentioned ... you need to sign your commits. (`git commit -s`). If you don't the DCO check can fail. I can override it this time, but you may find me less merciful in the future.
> 
> image

noted. (for next time)

**Pull request merged**
