### PR TITLE
Add client support for action profiles/selectors

### PR DESCRIPTION
**Pull request by Koushik-kopanati**
Modified p4rt-ctl to support action profiles/selectors. (NVFMSA-5854)

Signed-off-by: Koushik Kopanati <koushik.kopanati@intel.com>

### CODE REVIEW

**Comment by n-sandeep** [comment]
Can you please add the sample o/p of group and member dump here?

**Comment by Koushik-kopanati** [comment]
for action profile:
[root@localhost ipdk.recipe]# sudo  ./install/bin/p4rt-ctl dump-entries br0
Table entries for bridge br0:
  table=ingress.ipv4_host headers.ipv4.dst_addr=0x01010101 actions=action_profile_member_id(1)
  table=ingress.ipv4_host headers.ipv4.dst_addr=0x01010102 actions=action_profile_member_id(2)
  
for action selectors:
root@wp28:/home/admin2/drop8/ipdk-recipe# sudo  ./install/bin/p4rt-ctl dump-entries br0
Table entries for bridge br0:
  table=ingress.ipv4_host headers.ipv4.dst_addr=0x01010101 group_id(1)
  table=ingress.ipv4_host headers.ipv4.dst_addr=0x02020202 group_id(1)
  table=ingress.ipv4_host headers.ipv4.dst_addr=0xffffffff group_id(1)
  table=ingress.ipv4_host headers.ipv4.dst_addr=0xe0000001 group_id(1)

**Comment by ravi861** [comment]
Namrata asked to review for Tofino.
This should work for Tofino if it works for other targets. Ok to commit.

**Comment by Koushik-kopanati** [comment]
> Namrata asked to review for Tofino. This should work for Tofino if it works for other targets. Ok to commit.

I have a question we are still using sizeGet() here, will it not cause issue with tofino
as you mentioned in https://github.com/ipdk-io/stratum-dev/pull/50

**Comment by ffoulkes** [comment]
As a rule, the changelist comment should consist of a short heading followed by a more complete (and self-contained) description of the change.

The best commit heading provides a quick answer to the question, "what is the purpose of this commit?" Imagine that another developer has done a `git log --oneline` and is scanning the output to see what kind of changes have been made or whether a particular problem has been fixed. How would these stack up?
```
5652048 Fix build error when invoking grpc_cpp_plugin (#95)
e85698a Basic Pull Request gating (#94)
bdf819b Update krnlmon reference point and fix build issues (#93)
b162b35 Introduce daemon support for infrap4d for DPDK target (#89)
b5bb543 Set INSTALL_RPATH in libraries and executables (#86)
387b234 Provide extra control over dependencies setup (#87)
efb248b Address bandit warnings in p4rt-ctl (#90)
5ce8e5c Minor setup_env.sh maintenance (#88)
1167611 Add requirements text file for infrap4d (#91)
8ed693b Use find_package to locate grpc_cpp_plugin (#85)
6ef575b Integrate krnlmon into infrap4d instead of stratum (#84)
4d4c739 Update README file to reflect recent changes (#83)
```

The best commit comments give the reviewer the context they need to understand the changes and assess the correctness. 

Google's [Writing good CL descriptions](https://google.github.io/eng-practices/review/developer/cl-descriptions.html) document is an excellent guide to writing commit comments. I highly recommend it.

Also as a rule, you should limit references to resources that are not available to the reader.  NVFMSA-5854 is an internal Jira ticket number: useful for traceability at the project level (an argument for including it in the comment body) but too much arcane detail for the one-line summary.

**Review by ffoulkes — APPROVED** [review]
LGTM

**Pull request merged**
